defmodule SymphonyElixir.ControlPlane.ProjectRegistrySchemaContract do
  @moduledoc """
  Acceptance contract for the persistent Project Registry schema and path
  validation.

  Frozen by RES-339; the implementation (RES-340) must satisfy every check in
  this file. Do not edit this file to fit an implementation; change the
  contract through its owning issue instead.

  ## Frozen schema

  `SymphonyElixir.ControlPlane.ProjectRegistry` exposes exactly these fields:

  | field           | type                            | note                          |
  | --------------- | ------------------------------- | ----------------------------- |
  | `id`            | integer primary key             | stable row identity           |
  | `slug`          | string                          | stable project identifier     |
  | `name`          | string                          | display name                  |
  | `workflow_path` | string, absolute, unique        | path of the project's `WORKFLOW.md` |
  | `repo_path`     | string, optional, normalized    | path of the project's repo checkout |
  | `autostart`     | boolean                         | start the project with the Hub |
  | `assigned_port` | integer, optional               | port bound to the project     |
  | `created_at`    | datetime                        | timestamp                     |
  | `updated_at`    | datetime                        | timestamp                     |

  The table stores Symphony control-plane binding data only. Tracker issue or
  project data is never copied into it.

  ## Frozen validation

  * `validate_workflow_path(path, taken \\ [])` returns `:ok` for an absolute
    POSIX path (`/...`). It returns `{:error, :invalid_workflow_path}` for an
    empty, relative, or tilde path, and `{:error, :duplicate_workflow_path}`
    when the path is already present in `taken` (a plain list of already
    registered workflow paths).
  * `validate_repo_path(path)` returns `:ok` for `nil` (absent) or for a
    normalized path. It returns `{:error, :invalid_repo_path}` otherwise. A
    path is normalized when it is non-empty and contains no `.` or `..`
    segments, no `//`, and no trailing `/` except for the root `/`. Relative,
    absolute, and `~` prefixed paths are all allowed.

  ## Running this contract

  The file is intentionally not named `*_test.exs` so the default test suite
  does not pick it up:

      mix test test/symphony_elixir/control_plane/project_registry_schema_contract.exs

  Until RES-340 lands, every implementation-dependent check fails with the
  stable "implementation missing" message; that failure is the intended state
  of this contract.
  """

  use ExUnit.Case, async: true

  @impl_module_name "SymphonyElixir.ControlPlane.ProjectRegistry"

  @frozen_fields [
    :id,
    :slug,
    :name,
    :workflow_path,
    :repo_path,
    :autostart,
    :assigned_port,
    :created_at,
    :updated_at
  ]

  @frozen_types %{
    id: [:id, :integer],
    slug: [:string],
    name: [:string],
    workflow_path: [:string],
    repo_path: [:string],
    autostart: [:boolean],
    assigned_port: [:integer],
    created_at: [:utc_datetime, :utc_datetime_ms, :naive_datetime, :naive_datetime_ms, :date],
    updated_at: [:utc_datetime, :utc_datetime_ms, :naive_datetime, :naive_datetime_ms, :date]
  }

  @tracker_fields [
    :issue_id,
    :issue_key,
    :issue_url,
    :issue_state,
    :issue_status,
    :issue_title,
    :tracker_project_id,
    :tracker_project_name,
    :tracker_project_slug,
    :project_key,
    :labels,
    :priority,
    :state_name,
    :cycle_name,
    :assignee_email,
    :assignee_name
  ]

  test "freezes the exact projects field set" do
    module = impl_or_flunk!()
    fields = schema_fields(module)

    assert Enum.sort(fields) == Enum.sort(@frozen_fields),
           "projects schema must expose exactly the frozen fields, got: #{inspect(fields)}"
  end

  test "freezes stable types for the frozen fields" do
    module = impl_or_flunk!()

    types =
      schema_types(module) ||
        flunk("no schema type introspection available on #{inspect(module)}")

    for field <- @frozen_fields do
      assert Map.has_key?(types, field), "schema is missing a type for #{field}"

      assert Enum.member?(@frozen_types[field], base_type(types[field])),
             "unexpected schema type for #{field}: #{inspect(types[field])}"
    end
  end

  test "accepts an absolute workflow_path" do
    module = impl_or_flunk!()

    assert call(module, :validate_workflow_path, ["/abs/project", []]) == :ok
  end

  test "rejects a non-absolute workflow_path with a stable result" do
    module = impl_or_flunk!()

    for path <- ["relative/project", "~/code/project", ""] do
      assert call(module, :validate_workflow_path, [path, []]) ==
               {:error, :invalid_workflow_path},
             "expected {:error, :invalid_workflow_path} for #{inspect(path)}"
    end
  end

  test "rejects a duplicate workflow_path with a stable result" do
    module = impl_or_flunk!()

    assert call(module, :validate_workflow_path, ["/abs/project", ["/abs/project"]]) ==
             {:error, :duplicate_workflow_path}

    assert call(module, :validate_workflow_path, ["/abs/other", ["/abs/project"]]) == :ok
  end

  test "allows an absent repo_path" do
    module = impl_or_flunk!()

    assert call(module, :validate_repo_path, [nil]) == :ok
  end

  test "accepts a normalized repo_path" do
    module = impl_or_flunk!()

    for path <- ["/abs/repo", "relative/repo", "~/code/repo"] do
      assert call(module, :validate_repo_path, [path]) == :ok,
             "expected :ok for #{inspect(path)}"
    end
  end

  test "rejects a non-normalized repo_path with a stable result" do
    module = impl_or_flunk!()

    for path <- ["/abs/./repo", "/abs/../repo", "/abs/repo/", "//abs//repo", ""] do
      assert call(module, :validate_repo_path, [path]) ==
               {:error, :invalid_repo_path},
             "expected {:error, :invalid_repo_path} for #{inspect(path)}"
    end
  end

  test "keeps tracker issue and project data out of the registry" do
    refute Enum.any?(@frozen_fields, &(&1 in @tracker_fields)),
           "frozen field set must not contain tracker issue or project fields"

    case require_impl() do
      {:ok, module} ->
        fields = schema_fields(module)

        refute Enum.any?(fields, &(&1 in @tracker_fields)),
               "projects schema must not copy tracker issue or project data, found: " <>
                 inspect(Enum.filter(fields, &(&1 in @tracker_fields)))

      {:error, message} ->
        flunk(message)
    end
  end

  defp require_impl do
    module = String.to_atom(@impl_module_name)

    if Code.ensure_loaded?(module) do
      {:ok, module}
    else
      {:error,
       "implementation missing: #{@impl_module_name} (contract frozen by RES-339, " <>
         "implemented by RES-340)"}
    end
  end

  defp impl_or_flunk! do
    case require_impl() do
      {:ok, module} -> module
      {:error, message} -> flunk(message)
    end
  end

  defp schema_fields(module) do
    cond do
      function_exported?(module, :fields, 0) -> module.fields()
      function_exported?(module, :__schema__, 1) -> module.__schema__(:fields)
      true -> struct(module, []) |> Map.keys()
    end
  end

  defp schema_types(module) do
    if function_exported?(module, :__schema__, 1) do
      module.__schema__(:types)
    end
  end

  defp base_type({name, _, _}), do: name
  defp base_type(name), do: name

  defp call(module, fun, args) do
    arity = length(args)

    if function_exported?(module, fun, arity) do
      apply(module, fun, args)
    else
      flunk("contract function missing: #{inspect(module)}.#{fun}/#{arity}")
    end
  end
end
